### ISSUE TITLE
Error casting NSDate with DateTime, in show method 

### ISSUE THREAD

**Issue by saverMX** [alexsorokoletov/Xamarin.iOS.DatePickerDialog#2]

**Comment by alexsorokoletov** [comment]
@saverMX would you be kind as to provide detailed information on this issue?
What version of Xamarin.iOS do you have?

**Comment by orestesgaolin** [comment]
It's safe to provide starting, minimum and maximum dates as DateTime with specified Kind i.e:

`var minimumDate = new DateTime(1920, 1, 1).WithKind(DateTimeKind.Local);`

`WithTime()` is an extension method from MvvmCross.

**Comment by alexsorokoletov** [comment]
I wouldn't add any extra logic and this seems to be a Xamarin-specific thing how X handles `DateTime` -> `NSDate` conversion. @orestesgaolin provided a great tip on how to do that.

Closing for now.
