### ISSUE TITLE
Rotation Issues

### ISSUE THREAD

**Issue by blwillia** [alexsorokoletov/Xamarin.iOS.DatePickerDialog#4]
While in Landscape mode (LandscapeLeft), the picker is rotated twice.  When you have the picker visible and rotate the app, sometimes you see the white border.
![downloadattachment](https://user-images.githubusercontent.com/2389006/51214005-3b6a2b80-18e2-11e9-947a-f16222d8a0f2.png)

We have to adjust for this by setting the picker.Transform = CGAffineTransform.MakeRotation(0);

**Comment by alexsorokoletov** [comment]
@blwillia thank you for reporting the issue.
Wondering if you would be able to contribute the fix via pull request?

**Comment by alexsorokoletov** [comment]
@blwillia please try 1.0.3, should resolve your issue
